config/routes.rb
Project::Application.routes.draw do

  authenticated :user do
    root :to => 'home#signed_in'
  end

  root :to => "home#index"

  match "/top_up" => "users#top_up", :as => :top_up
  match "games/:id/hands/" => "games#get_current_hands", :as => :current_hand
  match "games/:id/cards/" => "games#get_communal_cards", :as => :communal_cards

  devise_for :users, :controllers => { :registrations => "registrations" }
  resources :users
  resources :games
  resources :hands
end

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <%= content_tag :div, msg, :id => "flash_#{name}" %>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<ul class="nav">
  <% if user_signed_in? %>
    <li>
    <%= link_to 'Logout', destroy_user_session_path, :method=>'delete' %>
    </li>
  <% else %>
    <li>
    <%= link_to 'Login', new_user_session_path %>
    </li>
  <% end %>
  <% if user_signed_in? %>
    <li>
    <%= link_to 'Edit account', edit_user_registration_path %>
    </li>
  <% else %>
    <li>
    <%= link_to 'Sign up', new_user_registration_path %>
    </li>
  <% end %>
</ul>

app/views/layouts/_topbar.html.erb
<nav class="top-bar">
        <ul class="title-area">
            <!-- Title Area -->
            <li class="name">
            <h1><a href="#">Dt354 Poker</a></h1>
            </li>
        <!-- Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone -->
            <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
        </ul>

    <section class="top-bar-section">
        <!-- Left Nav Section -->
        <ul class="left">
            <% if user_signed_in?%>
                <li class="divider"></li>
                <li><a href="#"><%= link_to 'Logout', destroy_user_session_path, :method=>'delete' %></a></li>
                <li class="divider"></li>
                <li><a href="#"><%= link_to 'Profile', current_user %></a></li>
                <li class="divider"></li>
                <li><a href="#"><%= link_to 'Poker', games_path %></a></li>
            <% else%>
            <li class="divider"></li>
            <li><a href="#"><%= link_to 'Sign up', new_user_registration_path %></a></li>
            <li class="divider"></li>
            <li><a href="#"><%= link_to 'Login', new_user_session_path %></a></li>
            <%end%>
        </ul>

        <!-- Right Nav Section -->
        <ul class="right">
            <li class="has-form">
                <form>
                    <div class="row collapse">
                        <div class="small-8 columns">
                            <input type="text">
                        </div>
                        <div class="small-4 columns">
                            <a href="#" class="alert button">Search</a>
                        </div>
                    </div>
                </form>
            </li>
        </ul>
    </section>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>   
        <title><%= content_for?(:title) ? yield(:title) : "Poker" %></title>
        <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Rails3 Devise Rspec Cucumber" %>">

        <%= stylesheet_link_tag "application", :media => "all" %>
        <%= javascript_include_tag "application" %>
        <%= csrf_meta_tags %>
            <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <%= yield(:head) %>
        <%if (current_user) %>
        <script type="text/javascript">
            window.currentUser = {
                id : "<%=current_user.id%>"
            }
        </script>
        <%end %>
    </head>
    <%= render 'layouts/topbar' %>
      
   
    <body class="<%= controller_name %> <%= action_name %>">
        <div id="container" class="container">
            <header>
                <%= render 'layouts/messages' %>
                <script type="text/template" id='new-poker-template'>
                    {{= id }}
                </script>   
            </header>
            <div id="main" role="main">
                <%= yield %>
            </div>
            <footer class="row">
                <div class="large-12 columns">
                        <hr>
                    <div class="row">
                        <div class="large-6 columns">
                            <p>© Martin Brennan</p>
                        </div>
                        <div class="large-6 columns">
                        </div>
                    </div>
                </div> 
            </footer>
        </div> <!--! end of #container -->
    </body>
</html>